# Create MWE regenie.wdl for RAP bgen/bgi/sample

In [4]:
module load Qctool/2.0.8

In [ ]:
qctool -g ~/UKBiobank_Yale_transfer/ukb39554_imputeddataset/ukb_imp_chr1_v3.bgen -s ~/UKBiobank_Yale_transfer/ukb39554_imputeddataset/ukb32285_imputedindiv.sample -incl-samples ~/mwe_regenie_rap/samples_keep.txt -incl-range 1:10177-17695 -og ~/mwe_regenie_rap/toy_data_chr1.bgen

In [10]:
qctool -g ~/UKBiobank_Yale_transfer/ukb39554_imputeddataset/ukb_imp_chr2_v3.bgen -s ~/UKBiobank_Yale_transfer/ukb39554_imputeddataset/ukb32285_imputedindiv.sample -incl-samples ~/mwe_regenie_rap/samples_keep.txt -incl-range 2:-11406 -og ~/mwe_regenie_rap/toy_data_chr2.bgen


Welcome to qctool
(version: 2.0.8, revision )

(C) 2009-2017 University of Oxford

Opening genotype files                                      : [******************************] (1/1,-0.8s,-1.2/s)

Input SAMPLE file(s):           "/home/dmc2245/UKBiobank_Yale_transfer/ukb39554_imputeddataset/ukb32285_imputedindiv.sample"
Output SAMPLE file:             "(n/a)".
Sample exclusion output file:   "(n/a)".

Input GEN file(s):
                                                    (not computed)  "snp-id-data-filtered:/home/dmc2245/UKBiobank_Yale_transfer/ukb39554_imputeddataset/ukb_imp_chr2_v3.bgen (bgen v1.2; 487409 unnamed samples; zlib compression)"
                                         (total 1 sources, number of snps not computed).
                      Number of samples: 487409
        Number of samples (post-filter): 100
Output GEN file(s):             "/home/dmc2245/mwe_regenie_rap/toy_data_chr2.bgen"
Output SNP position file(s):    (n/a)
Sample filter:                  ID_1 IN (10

In [13]:
qctool -g ~/UKBiobank_Yale_transfer/ukb39554_imputeddataset/ukb_imp_chr3_v3.bgen -s ~/UKBiobank_Yale_transfer/ukb39554_imputeddataset/ukb32285_imputedindiv.sample -incl-samples ~/mwe_regenie_rap/samples_keep.txt -incl-range 3:-62254 -og ~/mwe_regenie_rap/toy_data_chr3.bgen


Welcome to qctool
(version: 2.0.8, revision )

(C) 2009-2017 University of Oxford

Opening genotype files                                      : [******************************] (1/1,-8.4s,-0.1/s)

Input SAMPLE file(s):           "/home/dmc2245/UKBiobank_Yale_transfer/ukb39554_imputeddataset/ukb32285_imputedindiv.sample"
Output SAMPLE file:             "(n/a)".
Sample exclusion output file:   "(n/a)".

Input GEN file(s):
                                                    (not computed)  "snp-id-data-filtered:/home/dmc2245/UKBiobank_Yale_transfer/ukb39554_imputeddataset/ukb_imp_chr3_v3.bgen (bgen v1.2; 487409 unnamed samples; zlib compression)"
                                         (total 1 sources, number of snps not computed).
                      Number of samples: 487409
        Number of samples (post-filter): 100
Output GEN file(s):             "/home/dmc2245/mwe_regenie_rap/toy_data_chr3.bgen"
Output SNP position file(s):    (n/a)
Sample filter:                  ID_1 IN (10

In [15]:
module load Plink/1.9.10

In [ ]:
plink --bfile ~/UKBiobank/genotype_files_processed/090221_sample_variant_qc_final_callrate90/cache/UKB_genotypedatadownloaded083019.090221_sample_variant_qc_final_callrate90.filtered.extracted \
--keep ~/mwe_regenie_rap/samples_keep_plink.txt \
--mac 100 \
--make-bed \
--threads 10 \
--out ~/mwe_regenie_rap/toy_data_mac

In [23]:
module load Bgenix/1.1.8
bgenix -index -g ~/mwe_regenie_rap/toy_data_chr1.bgen


Welcome to bgenix
(version: 1.1.7, revision )

(C) 2009-2017 University of Oxford

bgenix: creating index for "/home/dmc2245/mwe_regenie_rap/toy_data_chr1.bgen" in "/home/dmc2245/mwe_regenie_rap/toy_data_chr1.bgen.bgi"...
bgenix: Opened "/home/dmc2245/mwe_regenie_rap/toy_data_chr1.bgen" with 0 variants...
Building BGEN index                                         :  (0/?,0.0s,0.0/s)

Thank you for using bgenix.


In [24]:
bgenix -index -g ~/mwe_regenie_rap/toy_data_chr2.bgen


Welcome to bgenix
(version: 1.1.7, revision )

(C) 2009-2017 University of Oxford

bgenix: creating index for "/home/dmc2245/mwe_regenie_rap/toy_data_chr2.bgen" in "/home/dmc2245/mwe_regenie_rap/toy_data_chr2.bgen.bgi"...
bgenix: Opened "/home/dmc2245/mwe_regenie_rap/toy_data_chr2.bgen" with 0 variants...
Building BGEN index                                         :  (0/?,0.0s,0.0/s)

Thank you for using bgenix.


In [25]:
bgenix -index -g ~/mwe_regenie_rap/toy_data_chr3.bgen


Welcome to bgenix
(version: 1.1.7, revision )

(C) 2009-2017 University of Oxford

bgenix: creating index for "/home/dmc2245/mwe_regenie_rap/toy_data_chr3.bgen" in "/home/dmc2245/mwe_regenie_rap/toy_data_chr3.bgen.bgi"...
bgenix: Opened "/home/dmc2245/mwe_regenie_rap/toy_data_chr3.bgen" with 0 variants...
Building BGEN index                                         :  (0/?,0.0s,0.0/s)

Thank you for using bgenix.


In [9]:
bgenix -index -g ~/mwe_regenie_rap/toy_data_chr6.bgen


Welcome to bgenix
(version: 1.1.7, revision )

(C) 2009-2017 University of Oxford

bgenix: creating index for "/home/dmc2245/mwe_regenie_rap/toy_data_chr6.bgen" in "/home/dmc2245/mwe_regenie_rap/toy_data_chr6.bgen.bgi"...
bgenix: Opened "/home/dmc2245/mwe_regenie_rap/toy_data_chr6.bgen" with 100 variants...
Building BGEN index                                         : [******************************] (100/100,0.0s,45909.7/s)

Thank you for using bgenix.



In [12]:
bgenix -index -g ~/mwe_regenie_rap/toy_data_chr1.bgen


Welcome to bgenix
(version: 1.1.7, revision )

(C) 2009-2017 University of Oxford

bgenix: creating index for "/home/dmc2245/mwe_regenie_rap/toy_data_chr1.bgen" in "/home/dmc2245/mwe_regenie_rap/toy_data_chr1.bgen.bgi"...
bgenix: Opened "/home/dmc2245/mwe_regenie_rap/toy_data_chr1.bgen" with 100 variants...
Building BGEN index                                         : [******************************] (100/100,0.0s,34820.3/s)

Thank you for using bgenix.



In [15]:
bgenix -index -g ~/mwe_regenie_rap/toy_data_chr2.bgen


Welcome to bgenix
(version: 1.1.7, revision )

(C) 2009-2017 University of Oxford

bgenix: creating index for "/home/dmc2245/mwe_regenie_rap/toy_data_chr2.bgen" in "/home/dmc2245/mwe_regenie_rap/toy_data_chr2.bgen.bgi"...
bgenix: Opened "/home/dmc2245/mwe_regenie_rap/toy_data_chr2.bgen" with 100 variants...
Building BGEN index                                         : [******************************] (100/100,0.0s,31374.6/s)

Thank you for using bgenix.



In [16]:
bgenix -index -g ~/mwe_regenie_rap/toy_data_chr3.bgen


Welcome to bgenix
(version: 1.1.7, revision )

(C) 2009-2017 University of Oxford

bgenix: creating index for "/home/dmc2245/mwe_regenie_rap/toy_data_chr3.bgen" in "/home/dmc2245/mwe_regenie_rap/toy_data_chr3.bgen.bgi"...
bgenix: Opened "/home/dmc2245/mwe_regenie_rap/toy_data_chr3.bgen" with 99 variants...
Building BGEN index                                         : [******************************] (99/99,0.0s,25824.2/s)

Thank you for using bgenix.



In [ ]:
/Users/dmc2245/cromwell/mwe_regenie_rap/toy_data_chr1.bgen	/Users/dmc2245/cromwell/mwe_regenie_rap/toy_data_chr1.bgi	/Users/dmc2245/cromwell/mwe_regenie_rap/toy_example.sample	1
/Users/dmc2245/cromwell/mwe_regenie_rap/toy_data_chr2.bgen	/Users/dmc2245/cromwell/mwe_regenie_rap/toy_data_chr2.bgi	/Users/dmc2245/cromwell/mwe_regenie_rap/toy_example.sample	2
/Users/dmc2245/cromwell/mwe_regenie_rap/toy_data_chr3.bgen	/Users/dmc2245/cromwell/mwe_regenie_rap/toy_data_chr3.bgi	/Users/dmc2245/cromwell/mwe_regenie_rap/toy_example.sample	3

In [6]:
import pandas as pd
pheno = pd.read_csv('~/mwe_regenie_rap/toy_example.sample', sep=" ")

In [7]:
pheno

ID_1     ID_2  missing  sex
0   5414209  5414209        0    1
1   5296052  5296052        0    2
2   4852763  4852763        0    2
3   5230840  5230840        0    2
4   1992219  1992219        0    2
..      ...      ...      ...  ...
95  4419678  4419678        0    2
96  5830444  5830444        0    2
97  2861021  2861021        0    2
98  2375434  2375434        0    1
99  1896578  1896578        0    1

[100 rows x 4 columns]

In [25]:
pheno= pheno.rename(columns={"ID_1": "FID", "ID_2": "IID", "pheno": "covar"})

In [26]:
pheno

FID      IID  covar  sex
0   5414209  5414209      0    1
1   5296052  5296052      0    2
2   4852763  4852763      0    2
3   5230840  5230840      0    2
4   1992219  1992219      0    2
..      ...      ...    ...  ...
95  4419678  4419678      0    2
96  5830444  5830444      0    2
97  2861021  2861021      0    2
98  2375434  2375434      0    1
99  1896578  1896578      0    1

[100 rows x 4 columns]

In [20]:
import numpy as np
import pandas as pd
 
data = np.random.randint(0,2 , size=100)

In [34]:
age = np.random.randint(40,70 , size=100)

In [21]:
data

array([1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0])

In [36]:
df = pd.DataFrame(data, columns=['pheno'])

In [37]:
df_age = pd.DataFrame(age, columns=['age'])

In [38]:
df_age

age
0    47
1    53
2    45
3    53
4    42
..  ...
95   61
96   55
97   42
98   43
99   56

[100 rows x 1 columns]

In [30]:
concatenated = pd.concat([pheno, df], axis="columns")

In [31]:
concatenated

FID      IID  covar  sex  pheno
0   5414209  5414209      0    1      1
1   5296052  5296052      0    2      0
2   4852763  4852763      0    2      0
3   5230840  5230840      0    2      0
4   1992219  1992219      0    2      0
..      ...      ...    ...  ...    ...
95  4419678  4419678      0    2      0
96  5830444  5830444      0    2      0
97  2861021  2861021      0    2      1
98  2375434  2375434      0    1      0
99  1896578  1896578      0    1      0

[100 rows x 5 columns]

In [39]:
concatenated_age = pd.concat([concatenated, df_age], axis="columns")

In [33]:
concatenated[["FID","IID", "pheno"]].to_csv("~/mwe_regenie_rap/pheno_toy.tsv", sep="\t", index=None)

In [40]:
concatenated_age

FID      IID  covar  sex  pheno  age
0   5414209  5414209      0    1      1   47
1   5296052  5296052      0    2      0   53
2   4852763  4852763      0    2      0   45
3   5230840  5230840      0    2      0   53
4   1992219  1992219      0    2      0   42
..      ...      ...    ...  ...    ...  ...
95  4419678  4419678      0    2      0   61
96  5830444  5830444      0    2      0   55
97  2861021  2861021      0    2      1   42
98  2375434  2375434      0    1      0   43
99  1896578  1896578      0    1      0   56

[100 rows x 6 columns]

In [41]:
concatenated_age[["FID","IID", "sex","age"]].to_csv("~/mwe_regenie_rap/covar_toy.tsv", sep="\t", index=None)

In [1]:
# Read into bgen file
from bgen_reader import open_bgen
bgen_file = '/mnt/vast/hpc/csg/UKBiobank/results/pleiotropy_AD_ARHI/111822_LDstore_files/regions_chr1_22/06/06_68849483_69523448.bgen'
bgen = open_bgen(bgen_file, verbose=False)

/tmp/5965237.1.csg.q/ipykernel_12542/2685489524.py:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Sized, KeysView, Sequence
/home/dmc2245/miniconda3/lib/python3.8/site-packages/sos_notebook/kernel.py:1334: DeprecationWarning: Kernel._parent_header is deprecated in ipykernel 6. Use .get_parent()
  msg['msg_id'] = self._parent_header['header']['msg_id']


In [2]:
# Print first 5 samples
print(bgen.samples[:5])
# ['sample_0' 'sample_1' 'sample_2' 'sample_3' 'sample_4']

['sample_0' 'sample_1' 'sample_2' 'sample_3' 'sample_4']


In [6]:
# Print first 5 variants
print(bgen.ids[:100]) #first 5
# ['6:31571218_C_T' '6:31571228_A_C' '6:31571296_A_G' '6:31571308_C_T' '6:31571330_C_A']

['6:68849483_A_G' '6:68849636_C_T' '6:68849644_C_T' '6:68849653_T_C'
 '6:68849689_C_G' '6:68849776_T_C' '6:68849781_T_C' '6:68849783_T_C'
 '6:68849802_C_T' '6:68849807_C_CG' '6:68849827_T_A' '6:68849836_C_T'
 '6:68849846_G_A' '6:68849860_A_T' '6:68849881_CA_C' '6:68849897_A_G'
 '6:68849909_G_T' '6:68849933_C_G' '6:68849948_T_G' '6:68849998_T_C'
 '6:68850024_A_G' '6:68850051_A_G' '6:68850100_A_T' '6:68850101_G_A'
 '6:68850106_A_T' '6:68850112_T_A' '6:68850112_T_G' '6:68850119_G_T'
 '6:68850150_T_C' '6:68850258_C_G' '6:68850322_T_C' '6:68850346_G_A'
 '6:68850350_C_T' '6:68850358_T_C' '6:68850444_C_A' '6:68850466_C_T'
 '6:68850468_C_T' '6:68850470_A_G' '6:68850519_C_T' 'rs79114683'
 '6:68850561_T_A' '6:68850618_C_T' '6:68850625_T_C' '6:68850672_C_T'
 '6:68850673_G_A' '6:68850691_G_A' '6:68850766_A_G' '6:68850774_T_A'
 '6:68850790_G_A' '6:68850812_C_T' '6:68850837_G_A' '6:68850838_A_T'
 '6:68850855_C_T' '6:68850914_A_G' '6:68850923_T_C' '6:68850974_A_C'
 '6:68850988_G_T' '6:68850989_A_T' '

In [4]:
print(bgen.nvariants)
# 43053

23418


In [5]:
## Read the probabilities of the first variant
probs = bgen.read(0)
print(probs)

[[[1. 0. 0.]]

 [[1. 0. 0.]]

 [[1. 0. 0.]]

 ...

 [[1. 0. 0.]]

 [[1. 0. 0.]]

 [[1. 0. 0.]]]


In [7]:
# Read into bgen file
from bgen_reader import open_bgen
bgen_file_1 = '/mnt/vast/hpc/csg/UKBiobank/results/pleiotropy_AD_ARHI/111822_LDstore_files/regions_chr1_22/01/01_48002576_48978188.bgen'
bgen_1 = open_bgen(bgen_file_1, verbose=False)

In [8]:
# Print first 100 variants
print(bgen_1.ids[:100])

['1:48002576_G_A' '1:48002588_G_A' '1:48002596_T_C' '1:48002631_G_A'
 '1:48002633_C_T' '1:48002641_G_A' '1:48002650_G_A' '1:48002697_G_T'
 '1:48002716_G_A' '1:48002723_A_G' '1:48002739_A_G' '1:48002745_C_T'
 '1:48002753_C_T' '1:48002772_G_A' '1:48002784_G_A' '1:48002790_G_A'
 '1:48002814_G_A' '1:48002818_G_A' '1:48002859_C_A' '1:48002903_G_A'
 '1:48002965_G_T' '1:48002966_T_A' '1:48002970_C_T' '1:48003001_T_C'
 '1:48003055_C_T' '1:48003056_G_A' '1:48003080_C_T' '1:48003081_T_C'
 '1:48003084_A_C' '1:48003091_G_T' '1:48003121_G_A' '1:48003156_C_A'
 '1:48003161_C_T' '1:48003169_A_G' '1:48003259_G_A' '1:48003287_G_A'
 '1:48003305_C_T' '1:48003306_G_A' '1:48003318_C_G' '1:48003323_C_T'
 '1:48003374_A_G' '1:48003382_AT_A' '1:48003474_G_A' '1:48003512_A_C'
 '1:48003558_C_T' '1:48003576_C_T' '1:48003592_C_T' '1:48003677_C_T'
 'rs512724' '1:48003679_C_T' '1:48003724_G_A' '1:48003762_C_T'
 '1:48003795_G_A' '1:48003813_G_A' '1:48003886_G_C' '1:48003953_T_TA'
 '1:48004001_G_T' '1:48004024_CTG_C' '

In [10]:
# Read into bgen file
from bgen_reader import open_bgen
bgen_file_2 = '/mnt/vast/hpc/csg/UKBiobank/results/pleiotropy_AD_ARHI/111822_LDstore_files/regions_chr1_22/02/02_195861164_196447456.bgen'
bgen_2 = open_bgen(bgen_file_2, verbose=False)

In [11]:
# Print first 100 variants
print(bgen_2.ids[:100])

['2:195861164_G_T' '2:195861181_G_C' '2:195861202_C_T' '2:195861203_G_A'
 '2:195861304_G_T' '2:195861315_T_C' '2:195861380_C_G' '2:195861420_A_C'
 '2:195861444_T_G' '2:195861451_T_C' '2:195861469_A_G' '2:195861545_T_TTG'
 '2:195861581_C_T' '2:195861582_G_A' '2:195861594_G_T' '2:195861604_T_C'
 '2:195861605_G_C' '2:195861613_T_C' '2:195861628_G_A' '2:195861629_T_C'
 '2:195861640_C_T' '2:195861641_G_A' '2:195861668_T_C' '2:195861718_C_T'
 '2:195861729_T_C' '2:195861791_A_AT' '2:195861792_T_C' '2:195861814_AT_A'
 '2:195861815_T_C' '2:195861817_C_T' '2:195861863_T_A' '2:195861865_G_A'
 '2:195861931_T_C' '2:195861961_T_C' '2:195862048_C_A' '2:195862048_C_T'
 '2:195862053_G_C' '2:195862145_T_C' '2:195862161_A_C' '2:195862171_G_C'
 '2:195862203_T_C' '2:195862238_T_C' '2:195862258_T_C' '2:195862308_A_G'
 '2:195862332_A_G' '2:195862334_T_C' '2:195862344_G_A' '2:195862352_G_A'
 '2:195862394_T_C' '2:195862427_C_G' '2:195862463_G_A' '2:195862465_G_C'
 '2:195862482_C_G' '2:195862504_A_G' '2:1958625

In [13]:
# Read into bgen file
from bgen_reader import open_bgen
bgen_file_3 = '/mnt/vast/hpc/csg/UKBiobank/results/pleiotropy_AD_ARHI/111822_LDstore_files/regions_chr1_22/03/03_173477285_175116539.bgen'
bgen_3 = open_bgen(bgen_file_3, verbose=False)

In [14]:
# Print first 100 variants
print(bgen_3.ids[:100])

['rs115530495' '3:173477307_A_T' '3:173477336_G_A' '3:173477392_G_A'
 '3:173477441_A_G' '3:173477455_C_G' '3:173477516_G_A' '3:173477564_T_C'
 '3:173477571_T_A' '3:173477585_G_T' '3:173477642_A_G' '3:173477703_A_G'
 '3:173477704_T_C' '3:173477773_C_G' '3:173477802_G_A' '3:173477835_C_T'
 '3:173477852_C_G' '3:173477901_A_G' '3:173477907_A_G' 'rs79574146'
 '3:173477943_G_A' '3:173477958_C_G' '3:173477960_C_A' '3:173477962_T_C'
 '3:173477967_C_G' '3:173477993_A_G' '3:173477997_C_A' '3:173478122_A_G'
 '3:173478158_G_A' 'rs1565196' '3:173478250_C_T' '3:173478304_A_C'
 '3:173478475_A_G' '3:173478481_A_C' '3:173478485_T_G' '3:173478579_C_CA'
 '3:173478673_C_A' '3:173478687_T_C' '3:173478733_C_T' '3:173478744_C_G'
 '3:173478799_G_A' '3:173478859_T_C' 'rs994148' '3:173478948_A_G'
 '3:173479073_C_G' '3:173479082_C_T' '3:173479124_G_A' '3:173479171_G_A'
 '3:173479176_G_A' '3:173479187_A_T' '3:173479205_G_T' '3:173479263_A_G'
 '3:173479273_A_C' '3:173479306_A_G' '3:173479312_G_A' '3:173479315_T_C'

In [19]:
# Common variables Columbia's cluster
UKBB_PATH=$HOME/UKBiobank
UKBB_yale=$HOME/UKBiobank_Yale_transfer
USER_PATH=$HOME/project
container_lmm=$HOME/containers/lmm.sif
container_marp=$HOME/containers/marp.sif
container_annovar=$HOME/containers/gatk4-annovar.sif
hearing_pheno_path=$UKBB_PATH/phenotype_files/hearing_impairment
tpl_file=$USER_PATH/bioworkflows/admin/csg.yml
formatFile_fastgwa=$USER_PATH/UKBB_GWAS_dev/data/fastGWA_template.yml
formatFile_bolt=$USER_PATH/UKBB_GWAS_dev/data/boltlmm_template.yml
formatFile_saige=$USER_PATH/UKBB_GWAS_dev/data/saige_template.yml
formatFile_regenie=$USER_PATH/UKBB_GWAS_dev/data/regenie_template.yml

In [20]:
# Workflows
lmm_sos=$USER_PATH/bioworkflows/GWAS/LMM.ipynb
anno_sos=$USER_PATH/bioworkflows/variant-annotation/annovar.ipynb
clumping_sos=$USER_PATH/bioworkflows/GWAS/LD_Clumping.ipynb
extract_sos=$USER_PATH/bioworkflows/GWAS/Region_Extraction.ipynb
snptogene_sos=$USER_PATH/UKBB_GWAS_dev/workflow/snptogene.ipynb

# LMM directories for imputed data
lmm_imp_dir_fastgwa=$UKBB_PATH/results/FastGWA_results/results_imputed_data
lmm_imp_dir_bolt=$UKBB_PATH/results/BOLTLMM_results/results_imputed_data
lmm_imp_dir_saige=$UKBB_PATH/results/SAIGE_results/results_imputed_data
lmm_imp_dir_regenie=$UKBB_PATH/results/REGENIE_results/results_imputed_data

# LMM directories for exome data
lmm_exome_dir_fastgwa=$UKBB_PATH/results/FastGWA_results/results_exome_data
lmm_exome_dir_bolt=$UKBB_PATH/results/BOLTLMM_results/results_exome_data
lmm_exome_dir_saige=$UKBB_PATH/results/SAIGE_results/results_exome_data
lmm_exome_dir_regenie=$UKBB_PATH/results/REGENIE_results/results_exome_data

In [21]:
## LMM variables 
## Specific to Bolt_LMM
LDscoresFile=$UKBB_PATH/LDSCORE.1000G_EUR.tab.gz
geneticMapFile=$UKBB_PATH/genetic_map_hg19_withX.txt.gz
covarMaxLevels=10
numThreads=20
bgenMinMAF=0.001
bgenMinINFO=0.8
lmm_job_size=1
ylim=0

### Specific to FastGWA (depeding if you run from Yale or Columbia)
####Yale's cluster
grmFile=$UKBB_PATH/results/FastGWA_results/results_imputed_data/UKB_Caucasians_phenotypeindepqc120319_updated020720removedwithdrawnindiv.grm.sp
####Columbia's cluster
grmFile=$UKBB_yale/results/FastGWA_results/results_imputed_data/UKB_Caucasians_phenotypeindepqc120319_updated020720removedwithdrawnindiv.grm.sp

### Specific to SAIGE
bgenMinMAC=4
trait_type=binary
loco=TRUE
sampleCol=IID

### Specific to REGENIE
bsize=1000
lowmem=$HOME/scratch60/
lowmem_dir=$HOME/scratch60/predictions
trait=bt
minMAC=4
maf_filter=0
geno_filter=0
hwe_filter=0
mind_filter=0
reverse_log_p=True

In [27]:
lmm_dir_regenie=~/test
lmm_sbatch_regenie=~/test/regenie_rap
phenoFile=~/mwe_regenie_rap/pheno_toy.tsv
covarFile=~/mwe_regenie_rap/covar_toy.tsv
phenoCol=pheno
covarCol=sex
qCovarCol=age
bgenMinINFO=0.8
bgenMinMAF=0.001
minMAC=4
maf_filter=0
geno_filter=0
hwe_filter=0
mind_filter=0
#Use the original bed files for the genotype array on regenie step1
bfile=~/mwe_regenie_rap/toy_data_mac.bed
# Use the imputed data hg19 to run the association analysis
genoFile=`echo ~/mwe_regenie_rap/toy_data_chr{1..3}.bgen`
sampleFile=~/mwe_regenie_rap/toy_example.sample
label_annotate=SNP

lmm_args="""regenie
    --cwd $lmm_dir_regenie 
    --bfile $bfile 
    --genoFile $genoFile
    --sampleFile $sampleFile
    --phenoFile $phenoFile 
    --covarFile $covarFile
    --formatFile $formatFile_regenie 
    --phenoCol $phenoCol
    --covarCol $covarCol  
    --qCovarCol $qCovarCol
    --bsize $bsize
    --lowmem_dir $lowmem_dir
    --trait $trait 
    --bgenMinMAF $bgenMinMAF 
    --bgenMinINFO $bgenMinINFO
    --maf_filter $maf_filter
    --geno_filter $geno_filter
    --hwe_filter $hwe_filter
    --mind_filter $mind_filter
    --minMAC $minMAC
    --job_size $lmm_job_size
    --ylim $ylim
    --label_annotate $label_annotate
    --no-annotate
    --reverse_log_p $reverse_log_p
    --numThreads $numThreads
    --container_lmm $container_lmm
    --container_marp $container_marp
"""

sos run ~/project/UKBB_GWAS_dev/admin/Get_Job_Script.ipynb csg\
    --template-file $tpl_file \
    --workflow-file $lmm_sos \
    --to-script $lmm_sbatch_regenie \
    --args "$lmm_args"

INFO: Running csg: Configuration for Columbia csg partition cluster
INFO: csg is completed.
INFO: csg output:   /home/dmc2245/test/regenie_rap
INFO: Workflow csg (ID=w90203f7801bead1a) is executed successfully with 1 completed step.



In [ ]:
module load Singularity/3.5.3

In [28]:
sos dryrun /home/dmc2245/project/bioworkflows/GWAS/LMM.ipynb \
    regenie:1\
    --cwd /home/dmc2245/test \
    --bfile /home/dmc2245/mwe_regenie_rap/toy_data_mac.bed \
    --genoFile /home/dmc2245/mwe_regenie_rap/toy_data_chr1.bgen /home/dmc2245/mwe_regenie_rap/toy_data_chr2.bgen /home/dmc2245/mwe_regenie_rap/toy_data_chr3.bgen\
    --sampleFile /home/dmc2245/mwe_regenie_rap/toy_example.sample\
    --phenoFile /home/dmc2245/mwe_regenie_rap/pheno_toy.tsv \
    --covarFile /home/dmc2245/mwe_regenie_rap/covar_toy.tsv \
    --formatFile /home/dmc2245/project/UKBB_GWAS_dev/data/regenie_template.yml \
    --phenoCol pheno\
    --covarCol sex  \
    --qCovarCol age\
    --bsize 1000\
    --lowmem_dir /home/dmc2245/scratch60/predictions\
    --trait bt \
    --bgenMinMAF 0.001 \
    --bgenMinINFO 0.8\
    --maf_filter 0\
    --geno_filter 0\
    --hwe_filter 0\
    --mind_filter 0\
    --minMAC 4\
    --job_size 1\
    --ylim 0\
    --label_annotate SNP\
    --no-annotate\
    --reverse_log_p True\
    --numThreads 20\
    --container_lmm /home/dmc2245/containers/lmm.sif\
    --container_marp /home/dmc2245/containers/marp.sif 

INFO: Checking regenie_qc: Select the SNPs and samples to be used based on maf, geno, hwe and mind options
HINT: singularity exec  /home/dmc2245/containers/lmm.sif /bin/bash /mnt/mfs/hgrcgrid/homes/dmc2245/project/UKBB_GWAS_dev/tmp151ii0xh/singularity_run_17011.sh
plink2 \
  --bfile /home/dmc2245/mwe_regenie_rap/toy_data_mac --mac 1 \
      \
  --write-snplist --write-samples --no-id-header \
  --threads 20 \
  --out /home/dmc2245/test/cache/toy_data_mac.qc_pass 


INFO: regenie_qc is completed.
INFO: regenie_qc output:   /home/dmc2245/test/cache/toy_data_mac.qc_pass.id /home/dmc2245/test/cache/toy_data_mac.qc_pass.snplist
INFO: Checking regenie_1: Run REGENIE step 1: fitting the null
HINT: singularity exec  /home/dmc2245/containers/lmm.sif /bin/bash /mnt/mfs/hgrcgrid/homes/dmc2245/project/UKBB_GWAS_dev/tmpovipfqv9/singularity_run_17011.sh
regenie \
  --step 1 \
  --bed /home/dmc2245/mwe_regenie_rap/toy_data_mac \
  --phenoFile /home/dmc2245/test/pheno_toy.regenie_phenotype \
  --covar

In [2]:
export PATH=$HOME/miniconda3/bin:$PATH
module load Singularity/3.5.3
sos dryrun /home/dmc2245/project/UKBB_GWAS_dev/workflow/snptogene.ipynb \
annovar     --cwd /home/dmc2245/UKBiobank/results_pleiotropy/REGENIE_results/results_exome_data/071023_Lung_fuction_whiteEUR/   \
--sumstatsFile /home/dmc2245/UKBiobank/results_pleiotropy/REGENIE_results/results_exome_data/071023_Lung_fuction_whiteEUR/UKB_exome_EUR_LungFunc_pcs_clean_FEV1_FVC_RATIO.regenie.snp_stats.gz  \
--bim_name /results/ukb23155_200Kexomes_annovar/091321_exome_bim_merge/ukb23155_chr1_chr22_091321.bim    \
--bimfiles      --p_filter 5e-08     --hg 38     --job_size 1     \
--humandb /mnt/vast/hpc/csg/isabelle/REF/humandb    --no-rsid      \
--xref_path /mnt/vast/hpc/csg/isabelle/REF/humandb     \
--container_annovar /home/dmc2245/containers/gatk4-annovar.sif     \
--container_lmm /home/dmc2245/containers/lmm.sif

INFO: Checking annovar_1: Get the list of significantly associated SNPs
HINT: singularity exec  /home/dmc2245/containers/lmm.sif Rscript /mnt/mfs/hgrcgrid/homes/dmc2245/project/UKBB_GWAS_dev/tmpfmorapjg/singularity_run_39255.R
library('dplyr')
# Import the sumstats file as dataframe
data <- read.table(gzfile('/home/dmc2245/UKBiobank/results_pleiotropy/REGENIE_results/results_exome_data/071023_Lung_fuction_whiteEUR/UKB_exome_EUR_LungFunc_pcs_clean_FEV1_FVC_RATIO.regenie.snp_stats.gz'), sep='\t', header=T)
# Filter SNPs with p-val <5e-08
# Subset data to obtain only chr, pos, snp, beta,se and p for gene mapping
# for the imputed data change the SNP field from rs to chr:pos:ref:alt 
if (FALSE){
  sig.p <- data %>%
     filter(P < 5e-08) %>%
     select(CHR, POS, REF, ALT, BETA, SE, P, SNP)
  #sig.p$SNP <- paste(sig.p$CHR, sig.p$POS, sig.p$REF, sig.p$ALT, sep=":")
  sig.p <- sig.p %>%
      select(SNP,BETA,SE,P)
} else {
  sig.p <- data %>%
  filter(P < 5e-08) %>%
  select(SNP,BETA,SE,P)
}